package com.example.themetapp.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ObjectModel(
    val objectID: String?,
    val objectId: Long?,
    val isHighlight: Boolean?,
    val accessionNumber: String?,
    val accessionYear: String?,
    val isPublicDomain: Boolean?,
    val primaryImage: String?,
    val primaryImageSmall: String?,
    val department: String?,
    val objectName: String?,
    val title: String?,
    val culture: String?,
    val period: String?,
    val dynasty: String?,
    val reign: String?,
    val portfolio: String?,
    val artistRole: String?,
    val artistPrefix: String?,
    val artistDisplayName: String?,
    val artistDisplayBio: String?,
    val artistSuffix: String?,
    val artistAlphaSort: String?,
    val artistNationality: String?,
    val artistBeginDate: String?,
    val artistEndDate: String?,
    val artistGender: String?,
    val artistWikidataURL: String?,
    val artistWikidataUrl: String?,
    val artistULANURL: String?,
    val artistUlanUrl: String?,
    val objectDate: String?,
    val objectBeginDate: Long?,
    val objectEndDate: Long?,
    val medium: String?,
    val dimensions: String?,
    val creditLine: String?,
    val geographyType: String?,
    val city: String?,
    val state: String?,
    val county: String?,
    val country: String?,
    val region: String?,
    val subregion: String?,
    val locale: String?,
    val locus: String?,
    val excavation: String?,
    val river: String?,
    val classification: String?,
    val rightsAndReproduction: String?,
    val linkResource: String?,
    val metadataDate: String?,
    val repository: String?,
    val objectURL: String?,
    val objectUrl: String?,
    val objectWikidataURL: String?,
    val isTimelineWork: Boolean?,
    val galleryNumber: String?,
) : Parcelable

data class Constituent(
    val constituentID: String,
    val constituentId: Long,
    val role: String,
    val name: String,
    val constituentUlanUrl: String,
    val constituentWikidataUrl: String,
    val gender: String,
)
